server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样取值介于 0到1之间，1则表示全部收集
        probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
